Dep updates: hardhat; chalk 4.x
- The current hardhat warn about our solc version; the updated version
  here officially supports newer solidity compiler versions.

- we use chalk but don't explicitly depend on it, and that apparently
  means we get a random version of chalk from who knows what
  sub-dependency by opaque nodejs magic dependency nonsense, which
  breaks with this if it decides to use one of the chalk v2 dependencies
  in the dep tree:

    npx hardhat run scripts/deploy-local-test.js --network localhost
    TypeError: chalk.greenBright is not a function
        at main (/home/jagerman/src/eth-sn-contracts/scripts/deploy-local-test.js:37:94)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

  Adding an explicit dependency on chalk ^4.1.2 fixes the issue.  (The
  latest is 5, but it also completely breaks so yay node ecosystem, as
  usual).