Fix ./test/cpp/.../bootstrap.min.js failing `pnpm test`
It's not clear how this was *ever* working because the default test
path is `./test/**/*.js`, which was picking up
`test/cpp/external/ethyl/external/oxen-logging/fmt/doc/_static/bootstrap.min.js`
which failed to compile/run with:

    An unexpected error occurred:

    Error: Bootstrap's JavaScript requires jQuery
        at Object.<anonymous> (/home/jagerman/src/eth-sn-contracts/test/cpp/external/ethyl/external/oxen-logging/fmt/doc/_static/bootstrap.min.js:6:37)
        at Module._compile (node:internal/modules/cjs/loader:1364:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
        at Module.load (node:internal/modules/cjs/loader:1203:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
        at Module.require (node:internal/modules/cjs/loader:1231:19)
        at require (node:internal/modules/helpers:177:18)
        at /home/jagerman/src/eth-sn-contracts/node_modules/.pnpm/mocha@10.2.0/node_modules/mocha/lib/mocha.js:414:36
        at Array.forEach (<anonymous>)
        at Mocha.loadFiles (/home/jagerman/src/eth-sn-contracts/node_modules/.pnpm/mocha@10.2.0/node_modules/mocha/lib/mocha.js:411:14)
     ELIFECYCLE  Test failed. See above for more details.

This fixes it to only include test/unit-js  when looking for hardhat
tests to run.